package com.devhub.api.domain.funcao;

public enum Funcao {
    DESENVOLVEDOR_BACKEND,
    DESENVOLVEDOR_FRONTEND,
    DESENVOLVEDOR_FULLSTACK,
    BANCO_DE_DADOS,
    PRODUCT_OWNER,
    QUALITY_ASSURANCE,
    WEB_DESIGNER

}
